[package]
name = "projects"
version = "0.1.0"
edition = "2024"

[dependencies]
dropshot = "0.16.0"
http = "1.3.1"
schemars = "0.8.22"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
